spring:
  application:
    name: koi-pond-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
    username: sa
    password: Password@sa
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        '[format_sql]': true
        connection:
          characterEncoding: utf8
          useUnicode: true
          charSet: UTF-8
        '[use_sql_comments]': true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 86400000  # 24 hours


logging:
  level:
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': INFO
    '[com.example.koipond]': DEBUG

 

server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      force: true
